nameOverride: kubernetes

rbac:
   create: true
  # serviceAccountName: datadog-sa
    serviceAccountName: datadog
clusterAgent:
  containerName: datadog-agent
  #image:
#    repository: datadog/datadog-agent
#    tag: 1.0.0
#    pullPolicy: Always
#  enabled: false

image:
  # This chart is compatible with different images, please choose one
  repository: datadog/agent               # Agent6
  # repository: datadog/dogstatsd         # Standalone DogStatsD6
 # tag: 6.5.2  # Use 6.5.2-jmx to enable jmx fetch collection
  tag: latest  # Use 6.5.2-jmx to enable jmx fetch collection
  pullPolicy: IfNotPresent
  ## It is possible to specify docker registry credentials
  ## See https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
  command: [ "/bin/bash", "-c", "--" ]
  args: [ "while true; do sleep 30; done;" ]
  pullSecrets:
    - name: datadog-secret

datadog:
#  proxy: ip-10-232-38-104.ec2.internal
   #ross: ip-10-232-38-104.ec2.internal
   #mgmt:
#  name: datadog-agent
  apikey: api-key
  apiKeyExistingSecret: datadog-kubernetes
  autoconf: true
  checksd:
#  confd:
#    kubernetes_state.yaml: |-
#       ad_identifiers:
#         - kube-state-metrics
#       init_config:
#       instances:
 #        - kube_state_url: http://%%host%%:8080/metrics
 #   kubelet.yaml: |-
 #       init_config:
 #       instances:
 #         - kubelet_port: 10514
 #         - kubelet_metrics_endpoint: http://%%host%%:10514/metrics

  apmEnabled: true
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 256Mi
  logsEnabled: true
  useCriSocketVolume: true
  leaderElection: true
  leaderLeaseDuration: 600


daemonset:
  useHostPort: true
  useHostNetwork: true

